### ISSUE TITLE
gestire assenza connessione db

### ISSUE THREAD

**Issue by mveronesi** [micheleveronesi/progetto_tecweb#37]
fare in modo che in caso il db sia offline non succedano vaccate nel sito

**Comment by mveronesi** [comment]
credo sia ok ma sarebbe il caso di ricontrollare

**Comment by SamueleVanini** [comment]
Pensare a come gestire gli errori nel caso la preparazione di una query o la sua esecuzione fallisca. Idea di leo e mia => metodo con numero di parametri variabile che gestisca l'inizializzazione ed esecuzione della query gestendone gli errori (ritorna l'oggetto di dominio richiesto o false). Ogni volta che si chiama una funzione per avere una query bisogna controllare che il return sia != false altrimenti va inserito un messaggio di errore nel template della pagina.
Risorse:
- https://www.php.net/manual/en/function.call-user-func-array.php
- https://www.php.net/manual/en/function.call-user-func-array.php

**Comment by LeonardoTredese** [comment]
Ciao belli qualcuno sta andando avanti con sta roba? o rimane dimeticata da tutti?

**Comment by mveronesi** [comment]
@LeonardoTredese dimenticata da tutti mi sa

**Comment by rizzostefano** [comment]
si voialtri i maghi del bekend

**Comment by LeonardoTredese** [comment]
Secondo voi ha senso metterla o teniamo l'errore mostrato sul sito di tecnologie web, che tra l'altro non penso di possa scavalcare

**Comment by mveronesi** [comment]
io lascerei quella di default che mostra il loro server, lo ha fatto anche pasticceria padovana

**Comment by LeonardoTredese** [comment]
d'accordo chiudo
