### ISSUE TITLE
controllo accessibilità finale

### ISSUE THREAD

**Issue by mveronesi** [micheleveronesi/progetto_tecweb#38]
- [x] menù per gli aiuti
- [ ] tag aria per i campi dei form
- [ ] raggiungibilità link da tag
- [x] colori diversi per tutti gli stati dei link
- [x] Link separati da almeno uno spazio
- [x] tutte le immagini non di contenuto inserite da css
- [x] non fare riferimenti spaziali come torna su
- [x] non fare riferimenti di colore come clicca il giallo
- [x] non nominare il nome di dio invano
- [x] tutti i contenuti mediatici devono degradare
- [ ] aggiunti gli aria role ai link per dargli un ruolo

chi più ne ha più ne metta

**Comment by rizzostefano** [comment]
non dovrebbe essere sempre necessario usare gli attributi aria nei form, andrebbero messi solo se il funzionamento del elemento differisce dal funzionamento standard
es, un bottone che al click fa apparire un div con del testo. In quel caso l'utilizzo di aria rende comprensibile il funzionamento del bottone anche a chi usa gli screen reader
