### ISSUE TITLE
Modifica controlli su inserimento e modifica articolo

### ISSUE THREAD

**Issue by SamueleVanini** [micheleveronesi/progetto_tecweb#45]
c'è un controllo che non lascia inserire markdown nel titolo di un articolo. Va modificato in modo che lasci inserire il custom tag per la lingua (? ), questo perché ora c'è un nuovo metodo per fare l'escape della lingua senza applicare tutte le regole di markdown (vedi issue #41 )

**Comment by LeonardoTredese** [comment]
Subito Begro, applico anche al js

**Comment by LeonardoTredese** [comment]
manca la conferma da parte del php
