### ISSUE TITLE
Includere documentazione del codice

### ISSUE THREAD

**Issue by SamueleVanini** [micheleveronesi/progetto_tecweb#48]
Aggiungere:
- [x] commenti al javascript
- [ ] commenti al php
- [ ] istruzioni su come inserire un articolo (latex e cosa può fare o no)

**Comment by LeonardoTredese** [comment]
@SamueleVanini manca solamente il commento di removeLanguage in escapeMarkdown.php e poi abbiamo finito con i commenti delle funzioni, Commentiamo pure il codice a casaccio?
