### ISSUE TITLE
Errore nelle regex per la lingua

### ISSUE THREAD

**Issue by LeonardoTredese** [micheleveronesi/progetto_tecweb#61]
La classe di mark down non genera correttamente gli span per la lingua con questo test:

Il più delle volte, chi porta uno strumento in laboratorio non ha idea dell'importanza delle corde. Spesso mi viene data carta bianca, oppure mi viene chiesto di mantenere la muta di corde già montata. 
Con questo articolo voglio dare qualche dritta ai meno esperti ed agli appassionati, dando alcune nozioni che consentano loro di scegliere autonomamente le corde che si adattino meglio al loro modo di suonare.

##Perchè è importante cambiare le corde?

Le corde sono senza dubbio la prima cosa che si usura in uno strumento. Questi sottili fili emettono una nota specifica venendo messi ad una specifica *tensione* su una certa *distanza*. Questa forza non è trascurabile, e soprattutto, non è trascurabile nel lungo periodo! Una corda, nella maggior parte dei casi, una volta montata rimane ad una tensione costante per diversi mesi se non anni! Questa forza *deforma la corda*, che con il tempo *perde la sua elasticità* e con essa la capacità di rimanere accordata e di vibrare liberamente. 
Questo, chiaramente, non è l'unico modo che hanno le corde di rovinarsi. Bisogna ricordare che le corde lavorano in condizioni pessime: strisciano sui tasti, sulle sellette del ponte, sul capotasto: sono parti che tipicamente possono essere causa di rottura precoce delle corde!
Inoltre, le corde sono a strettissimo contatto con le nostre mani. Per questo si sporcano e si ossidano molto velocemente, perdendo la brillantezza e la definizione tipica di un set di corde "fresco".  

##Come scegliere la giusta scalatura?

Quando si decide di comprare una muta di corde nuova, la prima cosa con cui ci si scontra è la scelta della scalatura. In commercio esistono set di corde di diverso diametro, e si identificano per lo spessore del mi cantino in pollici: *.009, .010, .012* associate a diciture come (?light), (?medium), (?heavy), e molte altre.
La scalatura delle corde è un parametro molto importante che influenza tantissimo la suonabilità: a parità di scala della chitarra (generalmente 25,5" per (?Fender) e 24,75" per (?Gibson)) a corde più spesse corrisponde un assetto più "rigido": sarà più difficile fare (?bending) o parti soliste particolarmente veloci.
È importante sottolineare la scala dello strumento, in quanto la muta di corde che si usa su una chitarra può non essere adatta per un'altra. Generalmente se per una (?Fender )le .009 sono uno strandard, per ottenere la stessa sensazione su una (?Gibson )dovremo passare ad una .010.
Altri accorgimenti da prendere sono relativi al vostro modo di suonare: se fate molto (?finger picking) o usate accordature aperte può essere molto comodo usare corde più spesse. Inoltre, ricordate: le corde spesse non suonano meglio come alcuni vogliono far credere! Suonate sempre con la muta più confortevole per le vostre mani.

##Diversi materiali e diversi rivestimenti:

Le corde negli anni sono state fatte in molti materiali. I più comuni sono senza dubbio nickel e acciaio. Le corde originariamente venivano fatte in nickel, a cui viene associato un suono caldo e corposo ed una ottima scorrevolezza. Le corde in acciaio invece, suonano più brillanti ed una volta amplificate, offrono maggior volume.
Al giorno d'oggi le corde sono tipicamente in acciaio placcato al nichel, apprezzate per la loro versatilità.
Alcuni produttori, come (?Elixir) e (?D'Addario), aggiungono ad alcuni loro set anche uno strato protettivo in poliestere, che allunga notevolmente la resistenza della muta allo sporco e alla corrosione permettendo alle corde di durare molto più a lungo. Alcuni puristi sostengono che il rivestimento influenzi in maniera sensibile il suono. Personalmente, penso che la maggior durata del set sia un beneficio difficilmente contestabile.

**Comment by LeonardoTredese** [comment]
Nel caso sia un problema con la regex avvertitemi che devo variare quella del js

era la regex?
- [ ] no
- [x] sì

**Comment by SamueleVanini** [comment]
@LeonardoTredese controlla che le regex siano uguali fra php e js

**Comment by LeonardoTredese** [comment]
Subito capo, prossima volta non chiudermi la issue
