### ISSUE TITLE
modificare css

### ISSUE THREAD

**Issue by rizzostefano** [micheleveronesi/progetto_tecweb#78]
bisogna modificare screen e mobile aggiungendo i vendor prefixes:

- [ ] Chrome: -webkit-   -> importante

- [ ] Firefox: -moz-    -> importante

- [ ] Internet Explorer: -ms-

- [ ] iOS: -webkit-

- [ ] Opera: -o-

- [ ] Safari: -webkit-

**Comment by mveronesi** [comment]
aggiungere css ad elenchi creati con markdown (non si vedono i pallini)
