### ISSUE TITLE
Caching iframe contatti

### ISSUE THREAD

**Issue by mveronesi** [micheleveronesi/progetto_tecweb#84]
Lighthouse lamenta di un rallentamento delle performance (grosso) nella pagina contatti (penso causato da un cattivo caching dell'iframe).
Questo merita un occhio di riguardo a mio parere, poi se secondo voi non ha importanza chiudete pure la issue.
https://web.dev/uses-long-cache-ttl/?utm_source=lighthouse&utm_medium=devtools

**Comment by rizzostefano** [comment]
questi sono problemi di chi gestisce il server generalmente, non dovremmo occuparcene noi (almeno in questa sede, se vuoi mettere nella relazione che poi questa cosa verrà presa in considerazione boh, fai pure)
